module.exports = {
  COMMAND_STAY_IN_PLACE: 101,
  COMMAND_MOVE_FORWARDS: 102,
  COMMAND_MOVE_BACKWARDS: 103,
  COMMAND_MOVE_RIGHT: 104,
  COMMAND_MOVE_LEFT: 105,
  COMMAND_TURN_LEFT: 106,
  COMMAND_TURN_RIGHT: 107,
  COMMAND_TURN_AROUND: 108,
  COMMANDS_ANALYSER: 'COMMANDS_ANALYSER',
  COMMANDS_INTERPRETER: 'COMMANDS_INTERPRETER'
};
