export enum Command {
  COMMAND_STAY_IN_PLACE,
  COMMAND_MOVE_FORWARDS,
  COMMAND_MOVE_BACKWARDS,
  COMMAND_MOVE_RIGHT,
  COMMAND_MOVE_LEFT,
  COMMAND_TURN_LEFT,
  COMMAND_TURN_RIGHT,
  COMMAND_TURN_AROUND
}
